baseURL = "https://gb.shoogle.net/england/"
languageCode = "en-US"
title = "England"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "england"

[taxonomies]
  shop = "shops"

